Update on-boarding UI
zeapo/Android-Password-Store pull request #1099
Opened 2020-09-14 11:15 UTC by Skrilltrax

## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Onboarding UI changes.

## :bulb: Motivation and Context
Our previous onboarding UI was a bunch of dialogs inside a single activity. This new UI makes it easy to extend the onboarding activity to add new features.

## :green_heart: How did you test it?
Tested all the onboarding options.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
## :camera_flash: Screenshots / GIFs

2020-09-14 11:20 UTC, Skrilltrax commented
I'm following [Buffer's package structure](https://buffer.com/resources/android-rethinking-package-structure/) here. We should fix all our packages like this once we are ready to push V2.

2020-09-14 12:01 UTC, msfjarvis requested changes

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="com.zeapo.pwdstore.ui.onboarding.activity.OnboardingActivity" />
```suggestion
        <activity android:name=".ui.onboarding.activity.OnboardingActivity" />
```

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="com.zeapo.pwdstore.ui.onboarding.activity.OnboardingActivity" />
Also, why the name re-use?

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/CloneFragment.kt
> +        binding.btnCloneRemote.setOnClickListener {
Drop the `btn` prefix, it doesn't hold much value in a strongly-typed ViewBinding world.

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/AndroidManifest.xml
> +            android:name="com.zeapo.pwdstore.ui.onboarding.activity.OnboardingActivity"
```suggestion
            android:name=".ui.onboarding.activity.OnboardingActivity"
```

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
> + *  SPDX-License-Identifier: GPL-3.0-only
leave this as-is.

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
> +    private fun createPermGrantedAction(block: () -> Unit): ActivityResultLauncher<String> =
Is the type necessary?

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
> +fun String.base64(): String = Base64.encodeToString(encodeToByteArray(), Base64.NO_WRAP)
Revert these

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
> +}
Move them to a separate `FragmentExtensions` file, things are getting pretty wild in here. Need to redistribute some more but that can go in a separate PR.

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
> +    canonicalPath.contains(getRepositoryDirectory().canonicalPath)
Revert this

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
> +fun Fragment.finish() = requireActivity().finish()
Move to `FragmentExtensions` along with the extensions at the bottom of this file.

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
> +    ContextCompat.checkSelfPermission(this, permission) == PackageManager.PERMISSION_GRANTED
Revert this

2020-09-14 12:01 UTC, msfjarvis commented on app/src/main/res/layout/fragment_repo_location.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Display1"
Let's try to stick with `MaterialComponents` text styling

2020-09-14 17:16 UTC, Skrilltrax commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
> +    private fun createPermGrantedAction(block: () -> Unit): ActivityResultLauncher<String> =
`ActivityResultContracts.RequestPermission()` always return `ActivityResultLauncher<String>`

2020-09-14 17:26 UTC, msfjarvis commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
> +    private fun createPermGrantedAction(block: () -> Unit): ActivityResultLauncher<String> =
yeah but do you need to explicitly set the type? I'd assume type inference catches it

2020-09-14 18:46 UTC, Skrilltrax commented on app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
> +    private fun createPermGrantedAction(block: () -> Unit): ActivityResultLauncher<String> =
Yeah, it does, AS was showing error for me earlier IDK why. Fixed now.

2020-09-15 12:17 UTC, msfjarvis commented
Removed reformat commit since it added too many changes to an already big PR, it can go in separately later.

2020-09-15 12:44 UTC, msfjarvis approved these changes
Everything appears to work in my testing

2020-09-15 16:23 UTC, merged

2020-09-24 07:03 UTC, FabianHenneke commented
While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?

2020-09-24 07:05 UTC, msfjarvis commented
> While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?

I'm not a fan of either option but adding a settings option feels like the less-likely-to-be-annoying choice w.r.t. UX.

2020-09-24 07:07 UTC, FabianHenneke commented
> > While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?
> 
> I'm not a fan of either option but adding a settings option feels like the less-likely-to-be-annoying choice w.r.t. UX.

Agreed. @Skrilltrax Is this something you could add before the release? I will update the remaining Wiki entries.

2020-09-24 07:39 UTC, msfjarvis commented
> > > While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?
> > 
> > 
> > I'm not a fan of either option but adding a settings option feels like the less-likely-to-be-annoying choice w.r.t. UX.
> 
> Agreed. @Skrilltrax Is this something you could add before the release? I will update the remaining Wiki entries.

He's got a fair bit of stuff going on at work, I'll do it.

2020-09-24 07:41 UTC, FabianHenneke commented
> > > > While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?
> > > 
> > > 
> > > I'm not a fan of either option but adding a settings option feels like the less-likely-to-be-annoying choice w.r.t. UX.
> > 
> > 
> > Agreed. @Skrilltrax Is this something you could add before the release? I will update the remaining Wiki entries.
> 
> He's got a fair bit of stuff going on at work, I'll do it.

Thanks! The Wiki entries should now reflect the flow for 1.12.0. I have also made them recommend in-app generation of SSH keys.

2020-09-24 07:55 UTC, msfjarvis commented
> > > > > While updating the Wiki entries, I noticed that it doesn't seem to be possible anymore to replace an existing SSH key from the on-boarding UI. Should we reintroduce the access to settings or just reset it if the repository is deleted?
> > > > 
> > > > 
> > > > I'm not a fan of either option but adding a settings option feels like the less-likely-to-be-annoying choice w.r.t. UX.
> > > 
> > > 
> > > Agreed. @Skrilltrax Is this something you could add before the release? I will update the remaining Wiki entries.
> > 
> > 
> > He's got a fair bit of stuff going on at work, I'll do it.
> 
> Thanks! The Wiki entries should now reflect the flow for 1.12.0. I have also made them recommend in-app generation of SSH keys.

The Wiki changes look good, I've created #1119 to add the settings button.