Use `GENERAL_SHOW_TIME` for decryption screen timeout
zeapo/Android-Password-Store pull request #2107
Opened 2022-09-06 20:46 UTC by Skrilltrax

Instead of adding another option, this uses the alternate approach mentioned in #1973. Let me know if any changes are required.

2022-09-06 21:00 UTC, msfjarvis requested changes
Once the changes are made, run the `detektBaseline` task and commit the changes.

2022-09-06 21:00 UTC, msfjarvis commented on app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
> +      val timeout = settings.getString(PreferenceKeys.GENERAL_SHOW_TIME)?.toIntOrNull() ?: 45
This needs to be 60 and pulled into a const.

2022-09-06 21:39 UTC, Skrilltrax commented on app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
> +      val timeout = settings.getString(PreferenceKeys.GENERAL_SHOW_TIME)?.toIntOrNull() ?: 45
The default value for `GENERAL_SHOW_TIME` is 45 at other places so I kept it 45 here as well.

2022-09-07 04:12 UTC, msfjarvis commented on app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
> +      val timeout = settings.getString(PreferenceKeys.GENERAL_SHOW_TIME)?.toIntOrNull() ?: 45
Then raise that to 60 as well.

2022-09-07 20:53 UTC, msfjarvis commented
Rebase and run Spotless + Detekt

2022-09-07 21:41 UTC, msfjarvis approved these changes

2022-09-07 21:49 UTC, merged