more robust switch actions in pgp settings
zeapo/Android-Password-Store pull request #3148
Opened 2024-08-03 14:32 UTC by agrahn

The PGP cache settings switches have been robustified a bit more. Now, every enable/disable action of the passphrase cache clears the same to enhance safety. This requires biom. authentification every time. If it fails (error/cancellation) the previous state is reverted to. Moreover, `onClick` listener is now used instead of `onCheckedChange` because the correct switch state is rendered immediately after the action has completed (esp. after auth cancellatiion by the user).

2024-08-03 15:12 UTC, msfjarvis requested changes
Some quick cleanups, you'll have to run `./gradlew ktfmtFormat` after applying these changes.

2024-08-03 15:12 UTC, msfjarvis commented on app/src/main/java/app/passwordstore/ui/settings/PGPSettings.kt
> +            if (checked) promptTitle = R.string.pref_passphrase_cache_authenticate_enable
```suggestion
            val promptTitle = if (checked) R.string.pref_passphrase_cache_authenticate_enable else R.string.pref_passphrase_cache_authenticate_disable
            
```

2024-08-03 15:12 UTC, msfjarvis commented on app/src/main/java/app/passwordstore/ui/settings/PGPSettings.kt
> +                    putBoolean(Feature.EnablePGPPassphraseCache.configKey, checked)
```suggestion
                    putBoolean(Feature.EnablePGPPassphraseCache.configKey, checked)
                    if (!checked) remove(PreferenceKeys.CLEAR_PASSPHRASE_CACHE)
```

2024-08-03 15:12 UTC, msfjarvis commented on app/src/main/java/app/passwordstore/ui/settings/PGPSettings.kt
> +                    activity.sharedPrefs.edit { remove(PreferenceKeys.CLEAR_PASSPHRASE_CACHE) }
```suggestion
```

2024-08-03 15:12 UTC, msfjarvis commented
Changes LGTM bar the stylistic nits, I'll test and merge this over the weekend.

2024-08-03 15:38 UTC, agrahn reviewed
Thanks, now the code looks cleaner.

2024-08-04 16:45 UTC, msfjarvis approved these changes

2024-08-04 16:53 UTC, merged